apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bookinfo-stagging
  namespace: bookinfo-ch-stagging
spec:
  pathname: https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/
  configRef:
    name: insecure-skip-verify
  type: HelmRepo

---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bookinfo-preprod
  namespace: bookinfo-ch-preprod
spec:
  type: Namespace
  pathname: bookinfo-ch-preprod
  configRef:
    name: insecure-skip-verify
  sourceNamespaces:
  - bookinfo-ch-stagging
  gates:
    annotations:
      slo-stagging-ready: approved

---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bookinfo-prod
  namespace: bookinfo-ch-prod
spec:
  pathname: https://raw.githubusercontent.com/rongzhus/subscription-examples/master/charts/repo/incubator/
  configRef:
    name: insecure-skip-verify
  type: HelmRepo

---
apiVersion: v1
data:
  insecureSkipVerify: "true"
kind: ConfigMap
metadata:
  name: insecure-skip-verify
  namespace:  bookinfo-ch-stagging

---
apiVersion: v1
data:
  insecureSkipVerify: "true"
kind: ConfigMap
metadata:
  name: insecure-skip-verify
  namespace:  bookinfo-ch-preprod

---
apiVersion: v1
data:
  insecureSkipVerify: "true"
kind: ConfigMap
metadata:
  name: insecure-skip-verify
  namespace:  bookinfo-ch-prod