apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: dev-placementrule
  namespace: bookinfo-project
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Dev
  clusterReplicas: 1
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: production-placementrule
  namespace: bookinfo-project
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Production
  clusterReplicas: 1
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: demo-placementrule
  namespace: bookinfo-project
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Demo
  clusterReplicas: 1

