apiVersion: monitoring.ibm.com/v1alpha1
kind: SyntheticBundle
metadata:
  name: bookinfo-synthetic
  namespace: bookinfo-project
  labels: 
    app: bookinfo
    release: 1.0.1
spec:
  applicationRef:
    name: bookinfo-app
  ingressRef:
    type: ingress
    name: bookinfo-demo
  interval: 1m
  tests: 
    - testName: Home page
      syntheticType: SeleniumLoad
      configuration:
        url: /productpage
    - testName: login
      configuration:
        url: /login
    - testName: logout
      configuration:
        url: /logout
    - testName: productapi
      configuration:
        url: /api/v1/products



