apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
  name: bookinfo-subscription
  namespace: bookinfo-project-1
spec:
  channel: bookinfo-entitlement/bookinfo-channel
  name: bookinfo
  packageFilter:
    version: 1.1.0
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: bookinfo
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo
    - path: spec.values
      value: |
        ingress:
          host: bam-all.fyre.ibm.com
        details:
          replicaCount: 1
        reviews:
          replicaCount: 1
        ratings:
          replicaCount: 1
        productpage:
          replicaCount: 2
        mysqldb:
          replicaCount: 1
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo-app-1
  namespace: bookinfo-project-1
spec:
  selector:
    matchExpressions:
    - key: purpose
      operator: In
      values:
      - icam-demo
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: dev-placementrule
  namespace: bookinfo-project-1
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Dev
  clusterReplicas: 1
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: production-placementrule
  namespace: bookinfo-project-1
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Production
  clusterReplicas: 1
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: demo-placementrule
  namespace: bookinfo-project-1
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Demo
  clusterReplicas: 1

