apiVersion: monitoring.ibm.com/v1alpha1
kind: SyntheticBundle
metadata:
  name: bookinfo-synthetic
  namespace: bookinfo-project-1
  labels: 
    app: bookinfo
    release: 1.0.1
spec:
  applicationRef:
    name: bookinfo-app-1
  ingressRef:
    type: ingress
    name: bookinfo-demo
  interval: 1m
  tests: 
    - testName: productapi
      configuration:
        url: /api/v1/products
    - testName: login
      configuration:
        url: /login

    



